---
# Conjur UI — serves at / (root landing page) AND /ui
# First page users see is the Conjur login
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ui
  namespace: conjur
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: conjur-ui
                port:
                  number: 80
