---
# Access via: kubectl -n securetask port-forward svc/webapp 8080:80
# Then open:  http://localhost:8080/app
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp
  namespace: securetask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: webapp
                port:
                  number: 80
