---
# ServiceAccount for the Conjur UI pod.
# Mapped to host/myapp/conjur-ui in Conjur policy for JWT authentication.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conjur-ui
  namespace: conjur
automountServiceAccountToken: true
